name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian:
    name: Build on Debian (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build project (Debian)
        run: |
          make distclean || true
          make

      - name: Archive Debian binaries
        uses: actions/upload-artifact@v2
        with:
          name: debian-binaries
          path: |
            ifshow_cmd
            ifnetshow_agent
            ifnetshow_client
            neighborshow_agent
            neighborshow

  alpine:
    name: Build on Alpine
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies on Alpine
        run: |
          apk update
          apk add gcc make musl-dev
      - name: Build project (Alpine)
        run: |
          make distclean || true
          make

      - name: Archive Alpine binaries
        uses: actions/upload-artifact@v2
        with:
          name: alpine-binaries
          path: |
            ifshow_cmd
            ifnetshow_agent
            ifnetshow_client
            neighborshow_agent
            neighborshow

  tinycore:
    name: Build on TinyCore
    runs-on: ubuntu-latest
    container:
      image: bensuperpc/tinycore:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies on TinyCore
        run: |
          tce-load -wi gcc
          tce-load -wi gcc_libs
          tce-load -wi gcc_libs-dev
          tce-load -wi gcc_base-dev
          tce-load -wi compiletc
      - name: Build project (TinyCore)
        run: |
          make distclean || true
          make

      - name: Archive TinyCore binaries
        uses: actions/upload-artifact@v2
        with:
          name: tinycore-binaries
          path: |
            ifshow_cmd
            ifnetshow_agent
            ifnetshow_client
            neighborshow_agent
            neighborshow
